

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springtest
    username: root
    password: 123456tg

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
server:
  port: 8080

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem



